name: nix-ci
on:
  pull_request:
    branches:
      - main

jobs:
  nix-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v31
      - name: Check whether the flake evaluates and run its tests
        run: nix flake check --all-systems
      - name: Lock
        run: nix flake lock
      - name: Check the lock file is up to date
        run: git diff --exit-code flake.lock
      - name: Fmt
        run: nix fmt -- **/*.nix
      - name: Check files are formatted
        run: git diff --exit-code

